config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'workers/profile' => 'profile#show', as: :worker_root  #redirect to profile after sign in

  resources :stores do
    resources :jobs
  end

  devise_for :workers, controllers: {registrations: 'workers/registrations'}
  devise_for :employers, controllers: {registrations: 'employers/registrations'}

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def home
  end

  def help
  end

  def terms
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "Quienes somos") %>
<h1>Aca ira quienes somos</h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contacto") %>
<h1>Esta sera la pagina de contacto</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Preguntas frecuentes") %>
<h1>Esta sera la pagina de preguntas frecuentes</h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Bienvenidos a PARTIME.com!</h1>
  <p>
    La mejor aplicación web para encontrar trabajos partime con velocidad.
  </p>
  <%= link_to "Crea tu cuenta", new_worker_registration_path, class: "btn btn-primary btn-lg"  %>
</div>

app/views/static_pages/terms.html.erb
<%= provide(:title, "Terminos y condiciones") %>
<h1>Aca iran los terminos y condiciones</h1>