config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'workers/profile' => 'profile#show', as: :worker_root  #redirect to profile after sign in

  resources :stores do
    resources :jobs
  end

  devise_for :workers, controllers: {registrations: 'workers/registrations'}
  devise_for :employers, controllers: {registrations: 'employers/registrations'}

end

app/models/store.rb
# == Schema Information
#
# Table name: stores
#
#  id               :integer          not null, primary key
#  name             :string
#  email            :string
#  manager_name     :string
#  manager_lastname :string
#  phone            :string
#  address          :string
#  company_id       :integer
#  employer_id      :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Store < ActiveRecord::Base
  validates :name, presence: {message: "no puede quedar quedar en blanco"}, uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX}
  validates :address, presence: true
  before_create :set_company_id, on: :create

  belongs_to :company
  belongs_to :employer
  has_many :jobs, dependent: :destroy

  scope :instance_company, lambda {|employer| where("stores.company_id = ?", employer.company_id )}
  ->{where(company_id: current_employer.company_id)}

  paginates_per 25

  protected
    def set_company_id
      self.company_id = Employer.find_by(id: self.employer_id).company_id
    end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_employer!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :validate_company, only: [:edit, :update, :destroy]

  def index
    @stores = Store.instance_company(current_employer).page(params[:page])
  end

  def show
    @store = Store.find(params[:id])
    @jobs = @store.jobs
    @job = @store.jobs.new
  end

  def new
    @store = Store.new
  end

  def create
    @store = current_employer.stores.new(store_params)
    if @store.save
      redirect_to stores_path
    else
      render :new
    end
  end

  def edit
    @store = Store.find(params[:id])
  end

  def update
    @store = current_employer.stores.find(params[:id])
    if @store.update(store_params)
      redirect_to store_path
    else
      render :edit
    end
  end

  def destroy
    @store = Store.find params[:id]
    @store.destroy
    flash[:success] = "Tienda Eliminada"
    redirect_to stores_path
  end

  private
    def store_params
      params.require(:store).permit(:name, :email, :address, :manager_name, :manager_lastname, :phone)
    end

    def validate_company
      @store = Store.find(params[:id])
      redirect_to stores_path unless current_employer.company_id == @store.company_id
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_job_form.html.erb
<h4>Nuevo Trabajo</h4>
<%= form_for ([@store, @job])  do |f| %>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :title, "Título" %>
      <%= f.text_field :title, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :start_date, "Fecha y Hora de inicio" %>
      <%= f.text_field :start_date, class: "form-control datetimepicker" %>
    </div>
    <div class="col-md-2">
      <%= f.label :finish_date, "Fecha y Hora de término" %>
      <%= f.text_field :finish_date, class: "form-control datetimepicker" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :body, "Descripción" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="col-md-2">
      </br><%= f.submit "Crear", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/stores/_jobs.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Trabajos</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Título</th>
          <th>Descripción</th>
          <th>Inicio</th>
          <th>Término</th>
          <th>Estado</th>
          <th>Postulantes/</br>Seleccionado</th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
          <% if job.persisted? %>
          <tr>
            <td><%= link_to job.title, store_job_path(@store, job) %></td>
            <td><%= truncate(job.body, {length: 30}) %></td>
            <td><%= job.start_date.strftime('%d/%m/%Y, %H:%M') %></td>
            <td><%= job.finish_date.strftime('%d/%m/%Y, %H:%M') %></td>
            <td><%= job.state %></td>
            <td><%= link_to "Postulantes", '#' %></td>
            <td><%= link_to "eliminar", store_job_path(@store, job), method: :delete, data: {confirm: "Estas seguro que deseas eliminar este trabajo"}  %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stores/edit.html.erb
<% provide(:title, "Nueva Tienda") %>
<div class="row">
  <div class="col-md-4">
    <h2>Nueva Tienda</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <%= form_for @store do |f| %>

      <%= f.label :name, "Nombre Tienda"  %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>

      <%= f.label :email, "Correo Electrónico" %>
      <%= f.email_field :email, autofocus: true, class: "form-control" %>

      <%= f.label :address, "Dirección"  %>
      <%= f.text_field :address, autofocus: true, class: "form-control" %>

      <%= f.label :manager_name, "Nombre Jefe de Tienda"  %>
      <%= f.text_field :manager_name, autofocus: true, class: "form-control" %>

      <%= f.label :manager_lastname, "Apellido Jefe de Tienda"  %>
      <%= f.text_field :manager_lastname, autofocus: true, class: "form-control" %>

      <%= f.label :phone, "Telefono"  %>
      <%= f.text_field :phone, autofocus: true, class: "form-control" %>

      <%= f.submit "Guardar cambios", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/stores/index.html.erb
<% provide(:title, "Tiendas") %>
<div class="row">
  <div class="col-md-4">
    <h2>Tiendas</h2>
  </div>
</div>

  <%= paginate @stores %>
<ul>
  <% @stores.each do |store| %>
      <li>
        <%= store.name %>
        <%= link_to "ver", store_path(store), class: "btn btn-link" %>
        <%= link_to "editar", edit_store_path(store), class: "btn btn-link" %>
        <%= link_to "eliminar", store_path(store), method: :delete, data: {confirm: "Seguro que deseas eliminar la tienda?"}  %></br>
      </li>
  <% end %>
</ul>

  <%= link_to "Crear tienda", new_store_path, class: "btn btn-primary"  %>

app/views/stores/new.html.erb
<% provide(:title, "Nueva Tienda") %>
<div class="row">
  <div class="col-md-4">
    <h2>Nueva Tienda</h2>
  </div>
</div>
<div class="row">
  <%= form_for @store do |f| %>
    <div class="col-md-3">
      <%= f.label :name, "Nombre Tienda"  %>
      <%= f.text_field :name, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :email, "Correo Electrónico" %>
      <%= f.email_field :email, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-md-3">
      <%= f.label :address, "Dirección"  %>
      <%= f.text_field :address, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-md-2"></br>
    <%= f.submit "Crear Tienda", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/stores/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h3><%= @store.name %></h3>
    <ul>
      <li>Correo electrónico: <%= @store.email %></li>
      <li>Nombre Jefe de Tienda: <%= "#{@store.manager_name} #{@store.manager_lastname}" %></li>
      <li>Telefono: <%= @store.phone %></li>
      <li>Dirección: <%= @store.address %></li>
    </ul>
    <%= link_to "editar información", edit_store_path(@store) %></br>
    <%= link_to "volver", stores_path %>
  </div>
</div>
<% if @jobs.present? %>
<%= render 'stores/jobs'  %>
<% end %>
<%= render 'stores/job_form' %>