config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'workers/profile' => 'profile#show', as: :worker_root  #redirect to profile after sign in

  resources :stores do
    resources :jobs
  end

  devise_for :workers, controllers: {registrations: 'workers/registrations'}
  devise_for :employers, controllers: {registrations: 'employers/registrations'}

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :text
#  start_date  :datetime
#  finish_date :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  store_id    :integer
#  worker_id   :integer
#  employer_id :integer
#  state       :string
#

class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  validates :start_date, presence: true
  validates :finish_date, presence: true

  belongs_to :store
  belongs_to :worker
  belongs_to :employer

  before_save :set_default_state, on: :create


  protected
    def set_default_state
      self.state = "awaiting"
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_employer!, only: [:new, :create, :edit, :update, :destroy]

  def show
    @store = Store.find(params[:store_id])
    @job = @store.jobs.find(params[:id])
  end

  def create
    @store = Store.find(params[:store_id])
    @job = @store.jobs.new(job_params)
    @job.employer_id = current_employer.id
    if @job.save
      redirect_to store_path(@store)
    else
      @jobs = @store.jobs
      render 'stores/show'
    end
  end

  def destroy
    @store = Store.find(params[:store_id])
    @job = @store.jobs.find(params[:id])
    if @job.destroy
      redirect_to store_path(@store), notice: "Se ha eliminado correctamente"
    else
      redirect_to store_path(@store), notice: "No se ha podido eliminar"
    end
  end

  def edit
    @store = Store.find(params[:store_id])
    @job = @store.jobs.find(params[:id])
  end

  def update
    @store = Store.find(params[:store_id])
    @job = @store.jobs.find(params[:id])
    if @job.update(job_params)
      redirect_to store_job_path(@store, @job), notice: "Se actualizo la información"
    else
      render :edit
    end
  end

  private
    def job_params
      params.require(:job).permit(:title, :body, :start_date, :finish_date)
    end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/edit.html.erb
<% provide(:title, "Editar tienda") %>
<%= form_for ([@store, @job])  do |f| %>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :title, "Título" %>
      <%= f.text_field :title, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :start_date, "Fecha y Hora de inicio" %>
      <%= f.text_field :start_date, value: f.object.start_date.strftime('%d/%m/%Y, %H:%M'), class: "form-control datetimepicker" %>
    </div>
    <div class="col-md-2">
      <%= f.label :finish_date, "Fecha y Hora de término" %>
      <%= f.text_field :finish_date, value: f.object.finish_date.strftime('%d/%m/%Y, %H:%M'), class: "form-control datetimepicker" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :body, "Descripción" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="col-md-2">
    </br><%= f.submit "Actualizar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<%= link_to 'volver', :back %>

app/views/jobs/index.html.erb
<%= provide(:title, "Trabajos #{@store.name}") %>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Título</th>
          <th>Descripción</th>
          <th>Fecha y Hora de Inicio</th>
          <th>Fecha y Hora de Término</th>
          <th>Estado</th>
          <th>Postulantes/Seleccionado</th>
        </tr>
      </thead>
      <tbody>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.title %></td>
            <td><%= job.body %></td>
            <td><%= job.start_date %></td>
            <td><%= job.finish_date %></td>
            <td><%= job.state %></td>
            <td><%= link_to "Postulantes", '#' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jobs/new.html.erb
<%= provide(:title, "Nuevo trabajo") %>
<div class="row">
  <div class="col-md-4">
    <h2>Nuevo trabajo</h2>
  </div>
</div>

<%= form_for ([@store, @job])  do |f| %>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :title, "Título" %>
      <%= f.text_field :title, autofocus: true, class: "form-control" %>
    </div>
    <div class="col-md-2">
      <%= f.label :start_date, "Fecha y Hora de inicio" %>
      <%= f.text_field :start_date, class: "form-control datetimepicker" %>
    </div>
    <div class="col-md-2">
      <%= f.label :finish_date, "Fecha y Hora de término" %>
      <%= f.text_field :finish_date, class: "form-control datetimepicker" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :body, "Descripción" %>
      <%= f.text_area :body, class: "form-control" %>
    </div>
    <div class="col-md-2">
      </br><%= f.submit "Crear", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/jobs/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h3>Tienda: <%= @store.name %></h3>
    <h4>Trabajo: <%= @job.title %></h4>
    <h4>Descripción:</h4>
    <p>
      Lugar: <%= @store.address %></br>
      Inicio: <%= @job.start_date.strftime('%d/%m/%Y, %H:%M') %></br>Termino: <%= @job.finish_date.strftime('%d/%m/%Y, %H:%M') %></br>
      <%= @job.body %>
    </p>
    <% if employer_signed_in? %>
      <%= link_to "editar", edit_store_job_path(@store, @job) %>
    <% end %>
  </div>
</div>