config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'help' => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'terms' => 'static_pages#terms'
  get 'workers/profile' => 'profile#show', as: :worker_root  #redirect to profile after sign in

  resources :stores do
    resources :jobs
  end

  devise_for :workers, controllers: {registrations: 'workers/registrations'}
  devise_for :employers, controllers: {registrations: 'employers/registrations'}

end

app/views/layouts/_employer_menu.html.erb
<li class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-user" data-toggle="dropdown"
  aria-haspopup="true" aria-expanded="true">Mi cuenta
  <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-user">
    <li><%= link_to "Administrar ofertas", '#' %></li>
    <li><%= link_to "Administrar tiendas", stores_path %></li>
    <li><%= link_to "Editar cuenta", edit_employer_registration_path %></li>
    <li><%= link_to "Cerrar sesión", destroy_employer_session_path, method: :delete%></li>
  </ul>
</li>

app/views/layouts/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <small>
      <ul>
        <li><%= link_to "Términos y condiciones", terms_path %></li>
        <li><%= link_to "Preguntas frecuentes", help_path %></li>
        <li><%= link_to "Contacto", contact_path %></li>
      </ul>
    </small>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a id="logo" class="navbar-brand" href="/">PARTIME</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "FAQ", help_path %></li>
          <li><%= link_to "Quienes somos", about_path %></li>
          <% if worker_signed_in? %>
            <%= render 'layouts/worker_menu' %>
          <% elsif employer_signed_in? %>
            <%= render 'layouts/employer_menu' %>
          <% else %>
            <li><%= link_to "Mi cuenta", new_worker_session_path %></li>
            <li><%= link_to "Cuenta empresa", employer_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_worker_menu.html.erb
<li class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-user" data-toggle="dropdown"
  aria-haspopup="true" aria-expanded="true">Mi cuenta
  <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdown-user">
    <li><%= link_to "Mi perfil", worker_root_path %></li>
    <li><%= link_to "Editar cuenta", edit_worker_registration_path %></li>
    <li><%= link_to "Mis trabajos", '#' %></li>
    <li><%= link_to "Cerrar sesión", destroy_worker_session_path, method: :delete %></li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'  %>
  </body>
</html>